# Generated by Django 5.2 on 2025-05-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonatos', '0002_alter_campeonato_imagem'),
        ('estadios', '0002_alter_estadio_imagem'),
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.campeonato')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadios.estadio')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_casa', to='times.time')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_fora', to='times.time')),
            ],
        ),
    ]
