# Generated by Django 5.2 on 2025-05-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data_partida',
            field=models.DateTimeField(),
        ),
    ]
