# Generated by Django 5.2 on 2025-05-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_alter_partida_data_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data_partida',
            field=models.DateField(),
        ),
    ]
