# Generated by Django 5.2 on 2025-05-06 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/%Y/%m')),
                ('username', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('data_nascimento', models.DateField()),
                ('acesso', models.CharField(max_length=100)),
                ('ativo', models.CharField(max_length=20)),
                ('pontos', models.IntegerField(default=0)),
            ],
        ),
    ]
