# Generated by Django 5.2 on 2025-05-11 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='imagens/estadio/')),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
