# Generated by Django 5.2 on 2025-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='imagem',
            field=models.ImageField(upload_to='imagens/estadios/'),
        ),
    ]
