# Generated by Django 5.2 on 2025-05-11 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_acesso_alter_usuario_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.IntegerField()),
                ('placar_fora', models.IntegerField()),
                ('jogador_gol', models.CharField(max_length=50)),
                ('minuto_gol', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
